name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '10'
      - run: npm install --save-dev jest ts-jest typescript
      - run: npm run test    
      - name: build 
        run: docker build -t vl96/node:latest ./
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCES_TOKIN }}
      - name: push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vl96/node:latest
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/
            docker run -d -p3000:3000 vl96/node:latest  
